<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Hrs.Fiscal.Core\Hrs.Fiscal.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QRCoder" Version="1.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>hrs-fiscal-cli</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Gui\index.html" LogicalName="Hrs.Fiscal.Cli.Gui.index.html" />
    <EmbeddedResource Include="Gui\hrs-logo.svg" LogicalName="Hrs.Fiscal.Cli.Gui.hrs-logo.svg" />
    <Content Remove="Gui\**" />
  </ItemGroup>

</Project>
